### ISSUE TITLE
Неверно отображается иконка онлайна

### ISSUE THREAD

**Issue by soredake** [Kesantielu/oldvk#11]
![1472503796](https://cloud.githubusercontent.com/assets/5204968/18067006/90e9902e-6e43-11e6-9641-ac66aa3d0ff1.png)

Firefox 48

**Comment by leet5** [comment]
Иначе смотрится совсем пусто

![default](https://cloud.githubusercontent.com/assets/23666610/22862510/3cb01178-f141-11e6-8698-2e82c0eedf49.png)
