### ISSUE TITLE
Undefined вместо элементов меню на эсперанто

### ISSUE THREAD

**Issue by ghost** [Kesantielu/oldvk#16]
[Скриншот](http://imglink.ru/pictures/02-04-17/25a598ab4c8f5b508a99a519637e4eba.jpg), на русском всё нормально.
В дополнениях не смыслю, поэтому даже предположить в чём проблема не могу :)
P.s. попробовал без noscript, тоже самое.

**Comment by Kesantielu** [comment]
Проблема в том, что расширение добавляет отсутствующий в новом дизайне текст, для которого нужно делать перевод. Пока переведены слова только для нескольких языков, позже в планах перевести больше.

Разве что теперь до перевода вместо `undefined` будет отображаться текст на английском языке.

**Comment by ghost** [comment]
Кажется так и есть. Спасибо!
