### ISSUE TITLE
Фото вылазят за пределы поста

### ISSUE THREAD

**Issue by soredake** [Kesantielu/oldvk#8]
после этого https://github.com/Kesantielu/oldvk/commit/476783fe82a83bc563c50d1dec0b23926cb7bddd коммита так
![1472462450](https://cloud.githubusercontent.com/assets/5204968/18047005/34b0ac44-6de3-11e6-966b-42e8b31a95a8.png)

**Comment by Kesantielu** [comment]
Greasemonkey?

**Comment by soredake** [comment]
Да, firefox 48

**Comment by soredake** [comment]
Сейчас почти всегда  фото вписываются после загрузки страницы, но иногда при переходе между группами не вписываются пока не обновишь страницу.

**Comment by soredake** [comment]
Кажется аддон на webextensions решил эту проблему.
